import { writeFileAtomic } from '../../utils/atomic.js';

export async function generateExampleFile(
  variables: ReadonlyArray<string>,
  outputPath: string,
): Promise<void> {
  const header = '# Auto-generated by env-surgeon\n';
  const lines = variables.map((v) => `${v}=`);
  await writeFileAtomic(outputPath, `${header}\n${lines.join('\n')}\n`);
}
